{"uuid": "810b2ee5-c7f0-467f-bb3b-94bf3bc4678f", "children": ["cacff67c-0c0e-427a-8f8b-c549b285a430", "4851d0b8-6884-4ba9-a066-53be0aa88ea9", "575cfc4c-37dd-42c3-980a-6cb088ed06a2", "61627f21-c6c1-4141-bfb5-4e9543c1f3f8", "a1213a9e-1f62-4915-abc2-877623d244da", "034921ba-1cfd-45db-9009-95699cbed81b", "00d4352f-c24e-4160-8082-a81241e96c26", "1ba66be2-a77b-4be4-85e0-fff2f0a145b8", "c0c790c2-4203-4db1-a6d4-c3e251b95a6d", "1f5d8794-f5e2-4714-b3a4-f927ae7694f3"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/tests/test_authorization_and_registration.py\", line 11, in driver\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 89, in __init__\n    self.service.start()\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1739220148263, "stop": 1739220148269}], "start": 1739220148263, "stop": 1739220148814}